services: docker
env:
- distro: centos7
  init: "/usr/lib/systemd/systemd"
  run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
- distro: centos6
  init: "/sbin/init"
  run_opts: ''
- distro: fedora24
  init: "/usr/lib/systemd/systemd"
  run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
- distro: ubuntu1604
  init: "/lib/systemd/systemd"
  run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
- distro: ubuntu1404
  init: "/sbin/init"
  run_opts: ''
- distro: ubuntu1204
  init: "/sbin/init"
  run_opts: ''
- distro: debian8
  init: "/lib/systemd/systemd"
  run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
before_install:
- docker pull v0rts/docker-${distro}-ansible:latest
script:
- container_id=$(mktemp)
- docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts}
  v0rts/docker-${distro}-ansible:latest "${init}" > "${container_id}"
- docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml
  --syntax-check
- docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml
- idempotence=$(mktemp)
- docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml
  | tee -a ${idempotence}
- 'tail ${idempotence} | grep -q ''changed=0.*failed=0'' && (echo ''Idempotence test:
  pass'' && exit 0) || (echo ''Idempotence test: fail'' && exit 1)

'
- docker exec --tty "$(cat ${container_id})" env TERM=xterm which java
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: h30Xvl49W5snO8hf2D2FbUzYicZBYXhcMbOhI0ylg4/jKsWgBePBaJYjMP7b9jEe9CIOjf5UNj2qqJR8Nny5tFgUcXO4wIJOBBenlmEnU31hkdMcMcEi1POcx1k6sZqyU3K6Dj3LUFJDEUZXs4xULTYezUFQuEoGO260qV34lKcWDzsIJy19qc6XNrTURrSLpSR4QBlWDuBKsc+k6i/PrbGrivq0UljEwMR7qgI8vT1uhRLUb/pqYURJ2Gevsz710J0mNGQsQlXBsKFTh1ExCNjBkI8490wH5alaqaSNJciwZdjMPqR/eDqZcaNSYpXen47AtCLTvwsFiaYQmcSnX07C/jl9xemm74I7wnvcPoZS4bnIMbywx0spd3lx9+yVLuK252Szzcici5h/TL5J9i9eWyyqWSmAkxAeeuyZldqwfzwYVGiqO97xvpsxk7fS4PYWL1ljF/uNY3bUwZfqgcY5mANBG5GAhcZ3MzjstGoqabVvnzcj2PDi1BUTonaC9UjbylhiO8BwGbCKFJrpsXJzV7cFkhpwJTtSkKgny0UE0iFTCX+Yl2FBGCyVjESlZg/dhBPPPyliGT2zwJ+bmuxndtxuHC17s5s4qm5QXN6f8h8DqyOCqXIqRLE7MSvaHrDAD3jtuTfqTIHJw8gte+pebNJlSmtKDJIRGub9Aig=
