---
- name: Install Git
  become: yes
  yum: name=git state=present

- name: Install Java jdk 1.8
  become: yes
  yum: name=java-1.8.0-openjdk state=present

- name: Install Curl
  become: yes
  yum: name=curl state=present


- name: Setup jenkins repo
  become: yes
  get_url:
    url: "{{ jenkins_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo

- name: Add repo GPG key
  become: yes
  rpm_key:
    state: present
    key: "{{ jenkins_repo_key_url }}"



- name: Make sure jenkins is installed and enabled
  become: yes
  yum: name=jenkins state=present
  notify: restart jenkins 



- name: Install Jenkins Plugins
  become: yes
  with_items:
  - name: cvs
  - name: dashboard-view
  - name: external-monitor-job
  - name: durable-task
  - name: git
  - name: git-client
  - name: git-server
  - name: github-api
  - name: ghprb
  - name: javadoc
  - name: junit
  - name: ldap
  - name: mailer
  - name: maven-plugin
  - name: pam-auth
  - name: plain-credentials
  - name: publish-over-ssh
  - name: ssh-agent
  - name: ssh-credentials
  - name: ssh-slaves
  - name: ssh-credentials
  - name: swarm
  get_url: dest="{{ jenkins_home }}/plugins/{{ item.name | mandatory }}.jpi"
           url="https://updates.jenkins-ci.org/latest/{{ item.name }}.hpi"
           owner=jenkins group=jenkins mode=0644
  notify:  restart jenkins


